#!/usr/bin/env bash

if [[ -z "$1" ]]; then
    echo "error: Argument not provided" >&2
    exit 1
fi

re='^[0-9]+$'
if ! [[ $1 =~ $re ]] ; then
   echo "error: Argument is not a number" >&2
   exit 1
fi

# format number and store into fn
printf -v fn "%02d" $1
touch "input/d${fn}_1.txt"
touch "input/d${fn}_1_test.txt"

# make dir and cd into it
mkdir "src/main/java/com/mival/d${fn}" && cd $_

for i in {1..2}; do
    touch "Day${fn}_${i}.java"

    cat > Day${fn}_${i}.java << EOL
    package com.mival.d${fn};

    import java.io.IOException;
    import java.util.ArrayList;
    import java.util.List;

    import com.mival.utils.Util;


    public class Day${fn}_${i} {
        public static void main(String[] args) {
            String fileName = "d${fn}_1" + (args.length != 0 && args[0].equals("test") ? "_test" : "");
            long result = 0;
            List<String> input = new ArrayList<>();
            try {
                input = Util.readInput(fileName);
            } catch (IOException ioException) {
                System.err.print(ioException);
            }


        }
    }
EOL
done
